sudo: false
os:
  - linux

dist:
  - trusty

language: rust

rust:
  - "1.19.0"
  - "1.20.0"
  - "1.21.0"
  - "1.22.0"
  - "1.23.0"
  - "1.24.0"
  - stable
  - beta

script:
  - cargo build --all-features
  - cargo test  --all-features

cache:
  cargo: true

