sudo: false
os:
  - linux

dist:
  - trusty

language: rust

rust:
  - 1.17.0
  - 1.18.0
  - stable
  - beta
  - nightly

script:
  - |
      cargo build --features timeconversions &&
      cargo test  --features timeconversions

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true

